POST http://localhost:8080/users/schedulePayment
Content-Type: application/json

{
  "id": "6",
  "originCC": "82631049200",
  "destinationCC": "123123",
  "value": 122,
  "dateTransfer": "2023-03-05"
}


###
