POST http://localhost:8080/users/schedulePayment
Content-Type: application/json

{
  "id": "4",
  "numberCC": "50610972300",
  "destinationAccount": "82631049200",
  "value": 122,
  "dateTransfer": "2023-03-05"
}


###
